# Generated by Django 5.1.5 on 2025-01-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idForum', models.AutoField(primary_key=True, serialize=False)),
                ('tytulPost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jednostka',
            fields=[
                ('idJednostka', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaJednostki', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='KategorieDiety',
            fields=[
                ('idKategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaKategorii', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaZakupow',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaListy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('idPrzepis', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaPrzepisu', models.CharField(max_length=50)),
                ('instrukcje', models.JSONField()),
                ('dataPublikacji', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('idRanking', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaRankingu', models.CharField(max_length=20)),
                ('typRankingu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('idUprawnienia', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaUprawnienia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('idUzytkownik', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaUzytkownika', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('haslo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ElementListy',
            fields=[
                ('idElement', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaElementu', models.CharField(max_length=50)),
                ('ilosc', models.FloatField()),
                ('zaznaczony', models.BooleanField()),
                ('jednostka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.jednostka')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.listazakupow')),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('idSkladnik', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaSkladnika', models.CharField(max_length=50)),
                ('ilosc', models.FloatField()),
                ('jednostka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.jednostka')),
            ],
        ),
        migrations.CreateModel(
            name='SkladnikPrzepisu',
            fields=[
                ('idSkladnikPrzepis', models.AutoField(primary_key=True, serialize=False)),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.przepis')),
                ('skladnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.skladnik')),
            ],
        ),
        migrations.AddField(
            model_name='przepis',
            name='autorPrzepisu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('idProfil', models.AutoField(primary_key=True, serialize=False)),
                ('preferencjeDiety', models.TextField()),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('tytulPost', models.CharField(max_length=255)),
                ('trescPost', models.TextField()),
                ('dataDodaniaPostu', models.DateField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posty', to='foodie_goodie_app.forum')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='OcenyPrzepisu',
            fields=[
                ('idOceny', models.AutoField(primary_key=True, serialize=False)),
                ('wartosc', models.IntegerField()),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='foodie_goodie_app.przepis')),
                ('oceniajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='listazakupow',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listy_zakupow', to='foodie_goodie_app.uzytkownik'),
        ),
        migrations.CreateModel(
            name='KomentarzePrzepisu',
            fields=[
                ('idKomentarz', models.AutoField(primary_key=True, serialize=False)),
                ('dataKomentarza', models.DateField()),
                ('trescKomentarza', models.CharField(max_length=250)),
                ('komentarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='foodie_goodie_app.komentarzeprzepisu')),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='foodie_goodie_app.przepis')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik'),
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('idWpis', models.AutoField(primary_key=True, serialize=False)),
                ('tresc', models.TextField()),
                ('dataDodania', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy', to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='ListyZDietami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.kategoriediety')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.listazakupow')),
            ],
            options={
                'unique_together': {('lista', 'kategoria')},
            },
        ),
        migrations.CreateModel(
            name='PrzepisyWRankingu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.IntegerField()),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.przepis')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.ranking')),
            ],
            options={
                'unique_together': {('ranking', 'przepis')},
            },
        ),
        migrations.CreateModel(
            name='UprawnieniaUzytkownikow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprawnienia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uprawnienia')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
            ],
            options={
                'unique_together': {('uprawnienia', 'uzytkownik')},
            },
        ),
        migrations.CreateModel(
            name='GlosyWpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaglosowano', models.BooleanField()),
                ('autorGlosu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
                ('wpis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.wpis')),
            ],
            options={
                'unique_together': {('wpis', 'autorGlosu')},
            },
        ),
    ]
