# Generated by Django 5.1.5 on 2025-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='glosy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
