# Generated by Django 5.1.5 on 2025-01-27 12:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='tytulPost',
            new_name='tytulForum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tytulPost',
        ),
        migrations.AddField(
            model_name='post',
            name='glosy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='img/upload/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='dataDodaniaPostu',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Jadlospis',
            fields=[
                ('idJadlospis', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('dataUtworzenia', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadlospisy', to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='JadlospisPrzepis',
            fields=[
                ('idJadlospisPrzepis', models.AutoField(primary_key=True, serialize=False)),
                ('dzienTygodnia', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('godzina', models.IntegerField(choices=[(0, 'Sniadanie'), (1, 'Lunch'), (2, 'Obiad'), (3, 'Podwieczorek'), (4, 'Kolacja')])),
                ('jadlospis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przepisy', to='foodie_goodie_app.jadlospis')),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.przepis')),
            ],
            options={
                'unique_together': {('jadlospis', 'przepis', 'dzienTygodnia', 'godzina')},
            },
        ),
    ]
