# Generated by Django 5.1.5 on 2025-01-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='wartosciodzywcze',
            field=models.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='Obserwowanie',
            fields=[
                ('idObserwowania', models.AutoField(primary_key=True, serialize=False)),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.przepis')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.uzytkownik')),
            ],
        ),
    ]
