# Generated by Django 5.1.5 on 2025-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='zdjecie',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
