# Generated by Django 5.1.5 on 2025-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementlisty',
            name='zaznaczony',
            field=models.BooleanField(default=False),
        ),
    ]
