# Generated by Django 5.1.5 on 2025-01-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementlisty',
            name='lista',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.listazakupow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementlisty',
            name='zaznaczony',
            field=models.BooleanField(default='default'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SzczegolyListy',
        ),
    ]
