# Generated by Django 5.1.5 on 2025-01-23 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0002_post_glosy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='tytulPost',
            new_name='tytulForum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tytulPost',
        ),
        migrations.AddField(
            model_name='post',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='posty_obrazki/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
