# Generated by Django 5.1.5 on 2025-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0002_przepis_wartosciodzywcze_obserwowanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przepis',
            name='wartosciodzywcze',
            field=models.JSONField(default=dict),
        ),
    ]
