# Generated by Django 5.1.5 on 2025-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0003_rename_tytulpost_forum_tytulforum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dataDodaniaPostu',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
