# Generated by Django 5.1.5 on 2025-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0003_alter_przepis_wartosciodzywcze'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='czasprzygotowania',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='przepis',
            name='porcja',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
