# Generated by Django 5.1.5 on 2025-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0003_alter_wpis_datadodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia/'),
        ),
    ]
