# Generated by Django 5.1.5 on 2025-01-26 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0004_alter_post_datadodaniapostu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='img/upload/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
