# Generated by Django 5.1.5 on 2025-01-20 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0004_alter_wpis_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='dataDodania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
