# Generated by Django 5.1.5 on 2025-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0004_przepis_czasprzygotowania_przepis_porcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='jednostka',
            name='minimalnaWartosc',
            field=models.FloatField(default=0.5),
        ),
    ]
