# Generated by Django 5.1.5 on 2025-01-21 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0005_alter_wpis_datadodania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadlospis',
            fields=[
                ('idJadlospis', models.AutoField(primary_key=True, serialize=False)),
                ('dataUtworzenia', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadlospisy', to='foodie_goodie_app.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='JadlospisPrzepis',
            fields=[
                ('idJadlospisPrzepis', models.AutoField(primary_key=True, serialize=False)),
                ('dzienTygodnia', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('godzina', models.TimeField()),
                ('jadlospis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przepisy', to='foodie_goodie_app.jadlospis')),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie_goodie_app.przepis')),
            ],
            options={
                'unique_together': {('jadlospis', 'przepis', 'dzienTygodnia', 'godzina')},
            },
        ),
    ]
