# Generated by Django 5.1.5 on 2025-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0006_jadlospis_jadlospisprzepis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadlospis',
            name='nazwa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
