# Generated by Django 5.1.5 on 2025-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0007_jadlospis_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadlospisprzepis',
            name='godzina',
            field=models.IntegerField(choices=[(0, 'Sniadanie'), (1, 'Lunch'), (2, 'Obiad'), (3, 'Podwieczorek'), (4, 'Kolacja')]),
        ),
    ]
