# Generated by Django 5.1.5 on 2025-01-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_goodie_app', '0008_alter_jadlospisprzepis_godzina'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='polubienia',
            field=models.IntegerField(default=0),
        ),
    ]
